# -*- coding: utf-8 -*-
"""cluster_labelling.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xpC0nzu95tgSOw5Ha2l0TrOLuTEjiMwc
"""

#label the clusters: Maximum weighted matching problem using Hungarian Algorithm

"""
input: 
cluster_labels - labels after running k-means
true_labels - labels from dataset 
k - number of distinct labels 
number_samples - number of datapoints/samples

Returns: 
cluster_labels - predicted labels to each datapoint

import dilb 
import numpy as np 

def labelling(cluster_labels, true_labels, k, number_samples): 

  matching = np.zeros((k,k), dtype = int)

  for i in range(number_samples): 
    matching[cluster_labels[i]][true_labels[i]] += 1 

  assignment = dilb.max_cost_assignment(dilb.matrix(matching))

  for i in range(number_samples):
    cluster_labels[i] = assignment[cluster_labels[i]]

    return cluster_labels

from sklearn.metrics import accuracy_score
import numpy as np 

def accuracy_analysis(accuracy_list): 
  average = np.average(accuracy_list
  standard_deviation = np.stf(accuracy_list)
  maximum = max(accuracy_list)

  print("Accuracy Analysis: Avergae = ", average, " ; Standard Deviation = ", standard deviation, "; Best Accuracy = ", maximum)

  return None